name: ProgramareConcurentaSiDistribuita
channels:
  - conda-forge
dependencies:
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2022.12.7
  - certifi=2022.12.7
  - cffi=1.15.1
  - charset-normalizer=2.1.1
  - click=8.1.3
  - cryptography=39.0.2
  - flask=2.2.3
  - idna=3.4
  - importlib-metadata=6.1.0
  - itsdangerous=2.1.2
  - jinja2=3.1.2
  - libffi=3.4.2
  - libsqlite=3.40.0
  - libzlib=1.2.13
  - markupsafe=2.1.2
  - ncurses=6.3
  - openssl=3.1.0
  - pip=23.0.1
  - pycparser=2.21
  - pyopenssl=23.0.0
  - pysocks=1.7.1
  - python=3.9.16
  - python_abi=3.9
  - readline=8.1.2
  - requests=2.28.2
  - setuptools=67.6.0
  - tk=8.6.12
  - tzdata=2022g
  - urllib3=1.26.15
  - werkzeug=2.2.3
  - wheel=0.40.0
  - xz=5.2.6
  - zipp=3.15.0
  - pip:
    - bidict==0.22.1
    - cachetools==5.3.0
    - flask-cors==3.0.10
    - flask-socketio==5.3.3
    - google-api-core==2.11.0
    - google-auth==2.16.2
    - google-cloud-core==2.3.2
    - google-cloud-firestore==2.10.0
    - google-cloud-pubsub==2.15.1
    - googleapis-common-protos==1.58.0
    - grpc-google-iam-v1==0.12.6
    - grpcio==1.51.3
    - grpcio-status==1.51.3
    - proto-plus==1.22.2
    - protobuf==4.22.1
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - python-engineio==4.4.0
    - python-socketio==5.8.0
    - rsa==4.9
    - six==1.16.0
